// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: merge.proto

package file_transfer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MergeService_MergeFiles_FullMethodName = "/file_transfer.MergeService/MergeFiles"
)

// MergeServiceClient is the client API for MergeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MergeServiceClient interface {
	MergeFiles(ctx context.Context, in *MergeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MergeResponse], error)
}

type mergeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMergeServiceClient(cc grpc.ClientConnInterface) MergeServiceClient {
	return &mergeServiceClient{cc}
}

func (c *mergeServiceClient) MergeFiles(ctx context.Context, in *MergeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MergeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MergeService_ServiceDesc.Streams[0], MergeService_MergeFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MergeRequest, MergeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MergeService_MergeFilesClient = grpc.ServerStreamingClient[MergeResponse]

// MergeServiceServer is the server API for MergeService service.
// All implementations must embed UnimplementedMergeServiceServer
// for forward compatibility.
type MergeServiceServer interface {
	MergeFiles(*MergeRequest, grpc.ServerStreamingServer[MergeResponse]) error
	mustEmbedUnimplementedMergeServiceServer()
}

// UnimplementedMergeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMergeServiceServer struct{}

func (UnimplementedMergeServiceServer) MergeFiles(*MergeRequest, grpc.ServerStreamingServer[MergeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method MergeFiles not implemented")
}
func (UnimplementedMergeServiceServer) mustEmbedUnimplementedMergeServiceServer() {}
func (UnimplementedMergeServiceServer) testEmbeddedByValue()                      {}

// UnsafeMergeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MergeServiceServer will
// result in compilation errors.
type UnsafeMergeServiceServer interface {
	mustEmbedUnimplementedMergeServiceServer()
}

func RegisterMergeServiceServer(s grpc.ServiceRegistrar, srv MergeServiceServer) {
	// If the following call pancis, it indicates UnimplementedMergeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MergeService_ServiceDesc, srv)
}

func _MergeService_MergeFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MergeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MergeServiceServer).MergeFiles(m, &grpc.GenericServerStream[MergeRequest, MergeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MergeService_MergeFilesServer = grpc.ServerStreamingServer[MergeResponse]

// MergeService_ServiceDesc is the grpc.ServiceDesc for MergeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MergeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file_transfer.MergeService",
	HandlerType: (*MergeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MergeFiles",
			Handler:       _MergeService_MergeFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "merge.proto",
}
