// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: checkpoint.proto

package stormgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckpointService_Checkpoint_FullMethodName = "/grpc.CheckpointService/Checkpoint"
)

// CheckpointServiceClient is the client API for CheckpointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckpointServiceClient interface {
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AckCheckpoint], error)
}

type checkpointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckpointServiceClient(cc grpc.ClientConnInterface) CheckpointServiceClient {
	return &checkpointServiceClient{cc}
}

func (c *checkpointServiceClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AckCheckpoint], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CheckpointService_ServiceDesc.Streams[0], CheckpointService_Checkpoint_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CheckpointRequest, AckCheckpoint]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CheckpointService_CheckpointClient = grpc.ServerStreamingClient[AckCheckpoint]

// CheckpointServiceServer is the server API for CheckpointService service.
// All implementations must embed UnimplementedCheckpointServiceServer
// for forward compatibility.
type CheckpointServiceServer interface {
	Checkpoint(*CheckpointRequest, grpc.ServerStreamingServer[AckCheckpoint]) error
	mustEmbedUnimplementedCheckpointServiceServer()
}

// UnimplementedCheckpointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckpointServiceServer struct{}

func (UnimplementedCheckpointServiceServer) Checkpoint(*CheckpointRequest, grpc.ServerStreamingServer[AckCheckpoint]) error {
	return status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedCheckpointServiceServer) mustEmbedUnimplementedCheckpointServiceServer() {}
func (UnimplementedCheckpointServiceServer) testEmbeddedByValue()                           {}

// UnsafeCheckpointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckpointServiceServer will
// result in compilation errors.
type UnsafeCheckpointServiceServer interface {
	mustEmbedUnimplementedCheckpointServiceServer()
}

func RegisterCheckpointServiceServer(s grpc.ServiceRegistrar, srv CheckpointServiceServer) {
	// If the following call pancis, it indicates UnimplementedCheckpointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckpointService_ServiceDesc, srv)
}

func _CheckpointService_Checkpoint_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CheckpointRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CheckpointServiceServer).Checkpoint(m, &grpc.GenericServerStream[CheckpointRequest, AckCheckpoint]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CheckpointService_CheckpointServer = grpc.ServerStreamingServer[AckCheckpoint]

// CheckpointService_ServiceDesc is the grpc.ServiceDesc for CheckpointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckpointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.CheckpointService",
	HandlerType: (*CheckpointServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Checkpoint",
			Handler:       _CheckpointService_Checkpoint_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "checkpoint.proto",
}
